# Generated by Django 3.2.6 on 2021-09-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hafapp', '0002_auto_20210916_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
    ]
